//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Langs {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a work.
        /// </summary>
        public static string addWork {
            get {
                return ResourceManager.GetString("addWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup is finish with error..
        /// </summary>
        public static string backupFinishedWithError {
            get {
                return ResourceManager.GetString("backupFinishedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup Type.
        /// </summary>
        public static string backupType {
            get {
                return ResourceManager.GetString("backupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business software:.
        /// </summary>
        public static string businessSoftware {
            get {
                return ResourceManager.GetString("businessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t continue backup. Business Software is open..
        /// </summary>
        public static string businessSoftwareOn {
            get {
                return ResourceManager.GetString("businessSoftwareOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not create destination folder..
        /// </summary>
        public static string cannotCreateDstFolder {
            get {
                return ResourceManager.GetString("cannotCreateDstFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check to encrypt files.
        /// </summary>
        public static string checkEncrypt {
            get {
                return ResourceManager.GetString("checkEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CryptoSoft Path:.
        /// </summary>
        public static string cryptosoftPath {
            get {
                return ResourceManager.GetString("cryptosoftPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cryptosoft path error..
        /// </summary>
        public static string cryptoSoftPathError {
            get {
                return ResourceManager.GetString("cryptoSoftPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cryptosoft path is not found..
        /// </summary>
        public static string cryptoSoftPathNotFound {
            get {
                return ResourceManager.GetString("cryptoSoftPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination.
        /// </summary>
        public static string destination {
            get {
                return ResourceManager.GetString("destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disk error..
        /// </summary>
        public static string diskError {
            get {
                return ResourceManager.GetString("diskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encrypted.
        /// </summary>
        public static string encrypt {
            get {
                return ResourceManager.GetString("encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to add work..
        /// </summary>
        public static string errorAddWork {
            get {
                return ResourceManager.GetString("errorAddWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to remove work..
        /// </summary>
        public static string errorRemoveWork {
            get {
                return ResourceManager.GetString("errorRemoveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File extension to encrypt:.
        /// </summary>
        public static string extensionFile {
            get {
                return ResourceManager.GetString("extensionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect Business Software Given!.
        /// </summary>
        public static string incorrectBusinessSoftware {
            get {
                return ResourceManager.GetString("incorrectBusinessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CryptoSoft Path incorrect!.
        /// </summary>
        public static string incorrectCryptosoftPath {
            get {
                return ResourceManager.GetString("incorrectCryptosoftPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Directory doesn&apos;t exist. Please enter a valid directory direction..
        /// </summary>
        public static string incorrectDestinationExist {
            get {
                return ResourceManager.GetString("incorrectDestinationExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a different path from the source..
        /// </summary>
        public static string incorrectDestinationSource {
            get {
                return ResourceManager.GetString("incorrectDestinationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect extension given!.
        /// </summary>
        public static string incorrectExtension {
            get {
                return ResourceManager.GetString("incorrectExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a valid name (1 to 20 characters)..
        /// </summary>
        public static string incorrectName {
            get {
                return ResourceManager.GetString("incorrectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Directory doesn&apos;t exist. Please enter a valid directory source..
        /// </summary>
        public static string incorrectSource {
            get {
                return ResourceManager.GetString("incorrectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  in .
        /// </summary>
        public static string inMessage {
            get {
                return ResourceManager.GetString("inMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language:.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No change since last backup..
        /// </summary>
        public static string noChangeSinceLastBackup {
            get {
                return ResourceManager.GetString("noChangeSinceLastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a work..
        /// </summary>
        public static string noSelectedWork {
            get {
                return ResourceManager.GetString("noSelectedWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No space for destination folder..
        /// </summary>
        public static string noSpaceDstFolder {
            get {
                return ResourceManager.GetString("noSpaceDstFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Every backup is finished.
        /// </summary>
        public static string progressBarDone {
            get {
                return ResourceManager.GetString("progressBarDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  finished with a total of .
        /// </summary>
        public static string progressBasResult {
            get {
                return ResourceManager.GetString("progressBasResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string searchName {
            get {
                return ResourceManager.GetString("searchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select All.
        /// </summary>
        public static string selectAll {
            get {
                return ResourceManager.GetString("selectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        public static string source {
            get {
                return ResourceManager.GetString("source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unvailable backup type..
        /// </summary>
        public static string unavailableBackupType {
            get {
                return ResourceManager.GetString("unavailableBackupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination directory doesn&apos;t found..
        /// </summary>
        public static string unavailableDstPath {
            get {
                return ResourceManager.GetString("unavailableDstPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source directory doesn&apos;t found..
        /// </summary>
        public static string unavailableSrcPath {
            get {
                return ResourceManager.GetString("unavailableSrcPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed: Unknown Error..
        /// </summary>
        public static string unknownError {
            get {
                return ResourceManager.GetString("unknownError", resourceCulture);
            }
        }
    }
}
