//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a work.
        /// </summary>
        public static string addWork {
            get {
                return ResourceManager.GetString("addWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasySave is already running!.
        /// </summary>
        public static string alreadyRunning {
            get {
                return ResourceManager.GetString("alreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup is finish with error..
        /// </summary>
        public static string backupFinishedWithError {
            get {
                return ResourceManager.GetString("backupFinishedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Progress.
        /// </summary>
        public static string backupProgress {
            get {
                return ResourceManager.GetString("backupProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Type.
        /// </summary>
        public static string backupType {
            get {
                return ResourceManager.GetString("backupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business software:.
        /// </summary>
        public static string businessSoftware {
            get {
                return ResourceManager.GetString("businessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t continue backup. Business Software is open..
        /// </summary>
        public static string businessSoftwareOn {
            get {
                return ResourceManager.GetString("businessSoftwareOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create destination folder..
        /// </summary>
        public static string cannotCreateDstFolder {
            get {
                return ResourceManager.GetString("cannotCreateDstFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete the destination folder.
        /// </summary>
        public static string cannotDelDstFolder {
            get {
                return ResourceManager.GetString("cannotDelDstFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Delete Works while they are Running!.
        /// </summary>
        public static string cantDeleteWork {
            get {
                return ResourceManager.GetString("cantDeleteWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Go to Settings while a Backup is Running!.
        /// </summary>
        public static string cantGoToSettings {
            get {
                return ResourceManager.GetString("cantGoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to encrypt files.
        /// </summary>
        public static string checkEncrypt {
            get {
                return ResourceManager.GetString("checkEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CryptoSoft Path:.
        /// </summary>
        public static string cryptosoftPath {
            get {
                return ResourceManager.GetString("cryptosoftPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptosoft path error..
        /// </summary>
        public static string cryptoSoftPathError {
            get {
                return ResourceManager.GetString("cryptoSoftPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptosoft path is not found..
        /// </summary>
        public static string cryptoSoftPathNotFound {
            get {
                return ResourceManager.GetString("cryptoSoftPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string destination {
            get {
                return ResourceManager.GetString("destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk error..
        /// </summary>
        public static string diskError {
            get {
                return ResourceManager.GetString("diskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted.
        /// </summary>
        public static string encrypt {
            get {
                return ResourceManager.GetString("encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add work..
        /// </summary>
        public static string errorAddWork {
            get {
                return ResourceManager.GetString("errorAddWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a destination file out of the source folder..
        /// </summary>
        public static string errorDstInSrc {
            get {
                return ResourceManager.GetString("errorDstInSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove work..
        /// </summary>
        public static string errorRemoveWork {
            get {
                return ResourceManager.GetString("errorRemoveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension to encrypt:.
        /// </summary>
        public static string extensionFile {
            get {
                return ResourceManager.GetString("extensionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Business Software Given!.
        /// </summary>
        public static string incorrectBusinessSoftware {
            get {
                return ResourceManager.GetString("incorrectBusinessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CryptoSoft Path incorrect!.
        /// </summary>
        public static string incorrectCryptosoftPath {
            get {
                return ResourceManager.GetString("incorrectCryptosoftPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory doesn&apos;t exist. Please enter a valid directory direction..
        /// </summary>
        public static string incorrectDestinationExist {
            get {
                return ResourceManager.GetString("incorrectDestinationExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a different path from the source..
        /// </summary>
        public static string incorrectDestinationSource {
            get {
                return ResourceManager.GetString("incorrectDestinationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Extension given!.
        /// </summary>
        public static string incorrectExtension {
            get {
                return ResourceManager.GetString("incorrectExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen a Size of 0ko (or you have entered an incorrect Size). No Size limit will be taken into account..
        /// </summary>
        public static string incorrectMaxSimultaneousFilesSize {
            get {
                return ResourceManager.GetString("incorrectMaxSimultaneousFilesSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid name (1 to 20 characters)..
        /// </summary>
        public static string incorrectName {
            get {
                return ResourceManager.GetString("incorrectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Extension given!.
        /// </summary>
        public static string incorrectPrioExtensionLabel {
            get {
                return ResourceManager.GetString("incorrectPrioExtensionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory doesn&apos;t exist. Please enter a valid directory source..
        /// </summary>
        public static string incorrectSource {
            get {
                return ResourceManager.GetString("incorrectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  in .
        /// </summary>
        public static string inMessage {
            get {
                return ResourceManager.GetString("inMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart EasySave to make this change effective..
        /// </summary>
        public static string languageMessage {
            get {
                return ResourceManager.GetString("languageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading logs..
        /// </summary>
        public static string loadLogsError {
            get {
                return ResourceManager.GetString("loadLogsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading settings.
        /// </summary>
        public static string loadSettingsError {
            get {
                return ResourceManager.GetString("loadSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading works..
        /// </summary>
        public static string loadWorksError {
            get {
                return ResourceManager.GetString("loadWorksError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Files Size that can be save simultaneously in ko (0 to none):.
        /// </summary>
        public static string maxSimultaneousFilesSize {
            get {
                return ResourceManager.GetString("maxSimultaneousFilesSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No change since last backup..
        /// </summary>
        public static string noChangeSinceLastBackup {
            get {
                return ResourceManager.GetString("noChangeSinceLastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a work..
        /// </summary>
        public static string noSelectedWork {
            get {
                return ResourceManager.GetString("noSelectedWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No space for destination folder..
        /// </summary>
        public static string noSpaceDstFolder {
            get {
                return ResourceManager.GetString("noSpaceDstFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Pourcentage.
        /// </summary>
        public static string percentageCopy {
            get {
                return ResourceManager.GetString("percentageCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Exentions:.
        /// </summary>
        public static string prioExtensionLabel {
            get {
                return ResourceManager.GetString("prioExtensionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every backup is finished.
        /// </summary>
        public static string progressBarDone {
            get {
                return ResourceManager.GetString("progressBarDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  finished with a total of .
        /// </summary>
        public static string progressBasResult {
            get {
                return ResourceManager.GetString("progressBasResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string searchName {
            get {
                return ResourceManager.GetString("searchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string selectAll {
            get {
                return ResourceManager.GetString("selectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string socket {
            get {
                return ResourceManager.GetString("socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client disconnected..
        /// </summary>
        public static string socketDeconnection {
            get {
                return ResourceManager.GetString("socketDeconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string source {
            get {
                return ResourceManager.GetString("source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works States:.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait (Band Width Saving).
        /// </summary>
        public static string stateBandWidthSaving {
            get {
                return ResourceManager.GetString("stateBandWidthSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait (Business Software On).
        /// </summary>
        public static string stateBusinessSofOn {
            get {
                return ResourceManager.GetString("stateBusinessSofOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait (Non-Priority Files).
        /// </summary>
        public static string stateNonPrioFiles {
            get {
                return ResourceManager.GetString("stateNonPrioFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string statePause {
            get {
                return ResourceManager.GetString("statePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string stateReady {
            get {
                return ResourceManager.GetString("stateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string stateRunning {
            get {
                return ResourceManager.GetString("stateRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unvailable backup type..
        /// </summary>
        public static string unavailableBackupType {
            get {
                return ResourceManager.GetString("unavailableBackupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination directory doesn&apos;t found..
        /// </summary>
        public static string unavailableDstPath {
            get {
                return ResourceManager.GetString("unavailableDstPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory doesn&apos;t found..
        /// </summary>
        public static string unavailableSrcPath {
            get {
                return ResourceManager.GetString("unavailableSrcPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed: Unknown Error..
        /// </summary>
        public static string unknownError {
            get {
                return ResourceManager.GetString("unknownError", resourceCulture);
            }
        }
    }
}
